# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Pollution Analysis
tagline:             'A CREU 2017 Blog'
description:         ''
url:                 https://hmc-cs-ctan.github.io/CREU-blog/
baseurl:             /CREU-blog/
paginate:            5

# About/contact
author:
  name:              Charleen Tan
  email:             ctan@hmc.edu

# Custom vars
version:             1.0.0
